### ISSUE TITLE
Add more test engines

### ISSUE THREAD

**Issue by evilenzo** [friendlyanon/cmake-init#117]
Since we already offer different choices for package management why not to give people opportunity to choose test engine? List of all test engines: https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C.2B.2B

But we might want to add only the most popular ones like googletest, doctest, boost.test etc.

Of course there is nothing hard about switching to another test engine but in my opinion, one of the purposes of this app is reducing boilerplate while configuring new project. Also I think that cmake-related configurations should be reduced as much as possible

**Comment by evilenzo** [comment]
> Of course there is nothing hard about switching to another test engine but in my opinion, one of the purposes of this app is reducing boilerplate while configuring new project. Also I think that cmake-related configurations should be reduced as much as possible

Also I think that there should be much more options for configuration like disable generation of docs for ex. This app generates a lot of things and not all of them are useful for some small projects. It would be cool to just generate app and jump into coding not tweaking. If maintainers agree with me I could open new issue about that. Appreciate your work though!

**Comment by evilenzo** [comment]
By the way, would also be cool to generate integration tests using pytest. That might be useful for microservices for ex.

**Comment by friendlyanon** [comment]
There is no benefit to adding more testing libraries. Catch2 is more like an example, but also my preferred testing library, because it doesn't depend on UB (like doctest) and it's not a Google product (like gtest).

Adding more would just be adding maintenance. The main purpose of this project is to show how to do the common things correctly when putting a CMake managed project together.

If you find yourself often making use of cmake-init, but you always do that same tweaks to your own project, you can also repackage it with your own modifications. The way cmake-init is packaged (just a `zipapp` invocation) is deliberately simple, so anyone can customize it to their own needs. In an ideal world, people wouldn't see the build system as "beneath them", but properly learned how to use it, so there would not be any need for a project like cmake-init.

For that reason, I'm not interested and I'm closing the issue.
